[project]
name = "TripAdvisor AI"
version = "0.1.0"
description = "An agentic AI using langgraph to recommend travel itenary information  in real-time"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.0",
]

[tool.uv.workspace]
members = [
    "TripAdvisor AI",
]
